source 'https://rubygems.org'

gem 'rake'
gem 'thin'
gem 'sinatra'
gem 'activerecord', '~> 4.1.10'
gem 'sinatra-activerecord'
gem 'sinatra-i18n'
gem 'sqlite3', '~> 1.3.6'
gem 'mysql2', '~> 0.3.0'
gem 'dalli'
gem 'rack-fiber_pool'
gem 'em-resolv-replace'
gem 'alphadecimal'
gem 'mime-types'
gem 'haml'
gem 'sass'
gem 'rack-test'
gem 'simplecov', '>= 0.4.0', :require => false, :group => :test
gem 'em-synchrony', :git => 'https://github.com/igrigorik/em-synchrony'
gem 'em-http-request'
gem 'tux'
gem 'rack-ssl-enforcer'
gem 'dotenv'
