source :rubygems

gem 'rake', '0.8.7'
gem 'thin'
gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sinatra-i18n'
gem 'sqlite3'
gem 'mysql2'
gem 'dalli'
gem 'rack-fiber_pool'
gem 'em-resolv-replace'
gem 'alphadecimal'
gem 'mime-types'
gem 'haml'
gem 'less'
gem 'rack-test'
gem 'simplecov', '>= 0.4.0', :require => false, :group => :test
gem 'em-synchrony', :git => 'https://github.com/igrigorik/em-synchrony.git'
gem 'em-http-request'
gem 'tux'
